GET http://localhost:1337/api


###

GET http://localhost:1337/api/621ca528bf328d6ee6c8ee8f

###

POST http://localhost:1337/api
Content-Type: application/json

{
    "name": "Background Remover",
    "endPoint": "https://lmaowtf.com",
    "description": "The description of the API in quick brief and we will truncate it here."
}

###

DELETE http://localhost:1337/api/621ca528bf328d6ee6c8ee8f

###

PATCH http://localhost:1337/api/621cac8a2e6485ac1c033682
Content-Type: application/json

{
    "name": "API",
    "endPoint": "https://removebg.com",
    "description": "Background Remover API Docs"
}
